import { Injectable } from '@angular/core';
import { Pasantia } from '../Models/Pasantia';
@Injectable({
  providedIn: 'root'
})
export class MockPasantiasService {

  constructor() { }

  getPasantiasActivas(): Pasantia[]{
    /*return [
      {fechaInicioBusqueda:  new Date("2020-08-20"),
      fechaFinBusqueda:  new Date("2020-09-20"),
      razonSocial: 'Hexacta',
      cargoACubrir:'Pasante en desarrollo',
      perfil:'Desarrollador fullstack',
      experiencia: 0,
      otrosConocimientos: 'Conocimientos en .NET y React JS. SQL server',
      otrosRequisitos:'Puntualidad',
      cantidadPasantes: 1,
      areaDesempenio: 'Sistemas',
      remuneracion: 15000,
      anioCursado: 5,
      duracionMeses: 12,
      horaEntrevistaDesde: 8,
      horaEntrevistaHasta: 16,
      seOfrece: 'Buen ambiente de trabajo',
      mail: 'hx@hexacta.com',
      sexo: 'Indistinto'},

      {fechaInicioBusqueda:  new Date("2020-08-10"),
      fechaFinBusqueda:  new Date("2020-09-05"),
      razonSocial: 'Vates',
      cargoACubrir:'Pasante en desarrollo',
      perfil:'Desarrollador backend',
      experiencia: 0,
      otrosConocimientos: 'Conocimientos en Java. SQL server, SCRUM',
      otrosRequisitos:'Buena predisposición',
      cantidadPasantes: 1,
      areaDesempenio: 'Sistemas',
      remuneracion: 16000,
      anioCursado: 4,
      duracionMeses: 6,
      horaEntrevistaDesde: 8,
      horaEntrevistaHasta: 16,
      seOfrece: 'Buen ambiente de trabajo',
      mail: 'arturo@vates.com',
      sexo: 'Indistinto'},

      {fechaInicioBusqueda:  new Date("2020-08-10"),
      fechaFinBusqueda:  new Date("2020-09-05"),
      razonSocial: 'Vates',
      cargoACubrir:'Pasante en testing',
      perfil:'Tester',
      experiencia: 0,
      otrosConocimientos: 'Ser alumno/a regular en cuarto año. Metodologías ágiles',
      otrosRequisitos:'Responsabilidad',
      cantidadPasantes: 2,
      areaDesempenio: 'Sistemas',
      remuneracion: 12000,
      anioCursado: 3,
      duracionMeses: 12,
      horaEntrevistaDesde: 10,
      horaEntrevistaHasta: 16,
      seOfrece: 'Posibilidad de extensión de contrato',
      mail: 'arturo@vates.com',
      sexo: 'Indistinto'},

      {fechaInicioBusqueda:  new Date("2020-08-10"),
      fechaFinBusqueda:  new Date("2020-09-05"),
      razonSocial: 'Globant',
      cargoACubrir:'Pasante en desarrollo',
      perfil:'Desarrollador frontend',
      experiencia: 0,
      otrosConocimientos: 'Conocimientos de HTML, CSS y Javascript. Angular (deseable). SQL server, SCRUM',
      otrosRequisitos:'Buena predisposición',
      cantidadPasantes: 1,
      areaDesempenio: 'Sistemas',
      remuneracion: 15000,
      anioCursado: 5,
      duracionMeses: 12,
      horaEntrevistaDesde: 8,
      horaEntrevistaHasta: 14,
      seOfrece: 'Buen ambiente de trabajo',
      mail: 'maria@globant.com',
      sexo: 'Indistinto'},

      {fechaInicioBusqueda:  new Date("2020-08-10"),
      fechaFinBusqueda:  new Date("2020-09-05"),
      razonSocial: 'Recursos informáticos',
      cargoACubrir:'Pasante IT',
      perfil:'Soporte técnico',
      experiencia: 0,
      otrosConocimientos: 'S.O Windows y Linux',
      otrosRequisitos:'Responsabilidad',
      cantidadPasantes: 1,
      areaDesempenio: 'Sistemas',
      remuneracion: 14500,
      anioCursado: 4,
      duracionMeses: 12,
      horaEntrevistaDesde: 8,
      horaEntrevistaHasta: 16,
      seOfrece: 'Buen ambiente de trabajo',
      mail: 'luis@rinformaticos.com',
      sexo: 'Indistinto'},

      {fechaInicioBusqueda:  new Date("2020-08-10"),
      fechaFinBusqueda:  new Date("2020-09-05"),
      razonSocial: 'Recursos informáticos',
      cargoACubrir:'Pasante IT',
      perfil:'Redes de información',
      experiencia: 0,
      otrosConocimientos: 'S.O Linux, conocimiento en redes. Alumno regular en quinto año. Inglés avanzado',
      otrosRequisitos:'Responsabilidad y puntualidad',
      cantidadPasantes: 1,
      areaDesempenio: 'Sistemas',
      remuneracion: 15000,
      anioCursado: 5,
      duracionMeses: 12,
      horaEntrevistaDesde: 8,
      horaEntrevistaHasta: 16,
      seOfrece: 'Buen ambiente de trabajo',
      mail: 'luis@rinformaticos.com',
      sexo: 'Indistinto'},
    ]*/
    return [];
  }
}
